[package]
name = "rigged_poker"
version = "1.0.0"
authors = []

[addresses]

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-framework-v1.16.0"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
